controller_list:
  - name: j2n4s200
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j2n4s200_joint_1
      - j2n4s200_joint_2
      - j2n4s200_joint_3
      - j2n4s200_joint_4
  - name: j2n4s200_gripper
    action_ns: gripper_command
    type: GripperCommand
    default: true    
    joints:
      - j2n4s200_joint_finger_1
      - j2n4s200_joint_finger_2